<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  
  <ItemGroup>
    <ProjectReference Include="..\LandTrust.Domain\LandTrust.Domain.csproj" />
	  <ProjectReference Include="..\LandTrust.Infrastructure\LandTrust.Infrastructure.csproj" />
  </ItemGroup>

</Project>
